import { expect, test } from "@playwright/test"

test.describe("RIPPLE Golden Path", () => {
  test("simulates TT Block, compares futures, and explains the recommendation", async ({ page }) => {
    await page.goto("/")
    await page.getByRole("link", { name: /Experience RIPPLE/ }).click()
    await expect(page).toHaveURL(/\/sandbox/)
    await expect(page.getByRole("heading", { name: "What decision do you want to test?" })).toBeVisible()
    await page.getByRole("link", { name: /^Operations/ }).click()
    await expect(page).toHaveURL(/view=operations/)
    const [scrollWidth, viewportWidth] = await page.evaluate(() => [document.documentElement.scrollWidth, window.innerWidth])
    expect(scrollWidth).toBeLessThanOrEqual(viewportWidth)

    const ttBuilding = page.getByRole("button", { name: /Select TT Block/ })
    await ttBuilding.focus()
    await ttBuilding.press("Enter")
    const simulate = page.getByRole("button", { name: /Simulate/ })
    await simulate.dblclick()

    await expect(page.getByText("RIPPLE COMPLETE")).toBeVisible({ timeout: 5000 })
    await expect(page.getByText("4,820", { exact: true }).first()).toBeVisible()
    await expect(page.getByText("96%", { exact: true }).first()).toBeVisible()
    await expect(page.locator(".kpi-item").filter({ hasText: "Campus stability" }).getByText("41", { exact: true })).toBeVisible()

    await page.getByRole("tab", { name: "OPTIMIZE" }).click()
    await expect(page.getByRole("heading", { name: "Absorb the disruption upstream" })).toBeVisible()
    await expect(page.getByRole("heading", { name: /Dynamic Reallocation/ })).toBeVisible()
    await expect(page.locator(".recommendation-metrics")).toContainText("Recovery improved")
    await expect(page.locator(".recommendation-metrics")).toContainText("Est. operational cost")
    await expect(page.getByText("87", { exact: true }).last()).toBeVisible()

    await page.getByRole("tab", { name: "WHY?" }).click()
    await expect(page.getByRole("heading", { name: "Why this decision?" })).toBeVisible()
    await expect(page.getByText(/Short-term scheduling complexity/)).toBeVisible()
  })

  test("resets mid-animation and supports an identical second run", async ({ page }) => {
    await page.goto("/sandbox?view=operations")
    const simulate = page.getByRole("button", { name: /Simulate/ })
    await simulate.click()
    await page.waitForTimeout(180)
    await page.getByRole("button", { name: "Reset", exact: true }).click()
    await expect(page.locator(".kpi-item").filter({ hasText: "Room utilization" }).getByText("82%", { exact: true })).toBeVisible()
    await expect(page.locator(".kpi-item").filter({ hasText: "Campus stability" }).getByText("87", { exact: true })).toBeVisible()

    await simulate.click()
    await expect(page.getByText("RIPPLE COMPLETE")).toBeVisible({ timeout: 5000 })
    await page.getByRole("button", { name: "Reset", exact: true }).click()
    await simulate.click()
    await expect(page.getByText("RIPPLE COMPLETE")).toBeVisible({ timeout: 5000 })
    await expect(page.getByText("4,820", { exact: true }).first()).toBeVisible()
    await expect(page.locator(".kpi-item").filter({ hasText: "Campus stability" }).getByText("41", { exact: true })).toBeVisible()
  })

  test("requires reset before rerunning and clears completed presentation when scenario changes", async ({ page }) => {
    await page.goto("/sandbox?view=operations")
    await page.getByRole("button", { name: "Simulate" }).click()
    await expect(page.getByText("RIPPLE COMPLETE")).toBeVisible({ timeout: 5000 })

    await expect(page.getByRole("button", { name: "Run", exact: true })).toBeDisabled()
    await expect(page.getByRole("button", { name: /Reset to rerun/ })).toBeDisabled()

    await page.getByLabel("Duration", { exact: true }).selectOption("4")
    await expect(page.getByText("RIPPLE T+00:00")).toBeVisible()
    await expect(page.getByRole("button", { name: "Simulate" })).toBeEnabled()
    await expect(page.getByText("Ready. Run the TT Block scenario to reveal the causal sequence.")).toBeVisible()
  })

  test("runs the interactive guided demo through the real controls", async ({ page }) => {
    await page.goto("/sandbox?guide=1")
    const dialog = page.getByRole("dialog")
    await expect(dialog).toContainText("Let’s simulate a campus disruption")
    await dialog.getByRole("button", { name: /Begin demo/ }).click()
    await expect(dialog).toContainText("Select the source")

    const ttBuilding = page.getByRole("button", { name: /Select TT Block/ })
    await ttBuilding.press("Enter")
    await expect(dialog).toContainText("Set the duration")
    await page.getByLabel("Duration", { exact: true }).selectOption("6")
    await expect(dialog).toContainText("Run the future")
    await page.getByRole("button", { name: "Simulate", exact: false }).click()
    await expect(page.getByText("RIPPLE COMPLETE")).toBeVisible({ timeout: 5000 })
    await expect(dialog).toContainText("Watch the ripple")
    await dialog.getByRole("button", { name: /Open Compare/ }).click()
    await expect(dialog).toContainText("Compare futures")
    await expect(page.getByRole("tab", { name: "COMPARE" })).toHaveAttribute("aria-selected", "true")
    await dialog.getByRole("button", { name: /Open Optimize/ }).click()
    await expect(dialog).toContainText("Optimize the decision")
    await expect(page.getByRole("tab", { name: "OPTIMIZE" })).toHaveAttribute("aria-selected", "true")
    await dialog.getByRole("button", { name: /Open WHY/ }).click()
    await expect(dialog).toContainText("Open WHY")
    await expect(page.getByRole("tab", { name: "WHY?" })).toHaveAttribute("aria-selected", "true")
    await dialog.getByRole("button", { name: /Finish demo/ }).click()
    await expect(dialog).toContainText("You just ran your first ripple")
  })

  test("loads a scenario preset, explores What If, and exposes the intervention brief", async ({ page }) => {
    await page.goto("/sandbox?view=operations")
    await page.getByText("Science Court Closure", { exact: true }).click()
    await expect(page.locator("#scenario-building")).toHaveValue("science-court")
    const whatIf = page.getByRole("slider", { name: "Closure duration" })
    await whatIf.fill("8")
    await expect(page.getByText("Apply 8h", { exact: false })).toBeEnabled()
    await page.getByRole("button", { name: /Apply 8h/ }).click()
    await page.getByRole("button", { name: /Simulate/ }).click()
    await expect(page.getByText("RIPPLE COMPLETE")).toBeVisible({ timeout: 5000 })
    await page.getByRole("tab", { name: "COMPARE" }).click()
    await expect(page.getByText("Temporary Rooms", { exact: true })).toBeVisible()
    await page.getByRole("tab", { name: "OPTIMIZE" }).click()
    await expect(page.getByText("Est. operational cost", { exact: true })).toBeVisible()
    await page.getByRole("tab", { name: "BRIEF" }).click()
    await expect(page.getByText("RIPPLE / decision brief")).toBeVisible()
    await expect(page.getByText("HUMAN APPROVAL REQUIRED", { exact: true })).toBeVisible()
    await expect(page.locator(".history-item")).toContainText("Science Court Closure")
  })
})
