"use client"

import { useMemo } from "react"
import { predictScenario } from "@/engine/predictiveModel"
import type { Scenario } from "@/types"

export function TrustPanel({ scenario }: { scenario: Scenario }) {
  const prediction = useMemo(() => predictScenario(scenario), [scenario])
  return <section className="trust-panel panel" id="model-trust"><div className="panel-header"><div className="panel-title"><span className="panel-code">07</span><h2>Model / trust</h2></div><span className="status-label">TRANSPARENCY</span></div><div className="trust-body"><div className="trust-summary"><div><span className="eyebrow">{prediction.inference.source === "local-neural-network" ? "Neural model confidence" : "Fallback status"}</span><strong>{prediction.inference.source === "local-neural-network" ? `${prediction.inference.confidence}%` : "ACTIVE"}</strong></div><p>{prediction.inference.source === "local-neural-network" ? prediction.inference.confidenceBasis : "Predictive model unavailable — deterministic simulation active."}</p></div><div className="trust-grid"><div><span className="metric-label">Prediction</span><strong>{prediction.inference.modelLabel}</strong></div><div><span className="metric-label">Training data</span><strong>Synthetic deterministic campus dataset</strong></div><div><span className="metric-label">Inference</span><strong>Local forward pass</strong></div><div><span className="metric-label">Simulation</span><strong>Deterministic causal rules</strong></div><div><span className="metric-label">Human approval</span><strong>Required</strong></div></div><div className="confidence-breakdown"><span className="metric-label">Model coverage</span><div><span>Data completeness</span><i style={{ width: "88%" }} /></div><div><span>Held-out evaluation</span><i style={{ width: `${prediction.inference.source === "local-neural-network" ? prediction.inference.confidence : 0}%` }} /></div><div><span>Scenario coverage</span><i style={{ width: `${prediction.confidence}%` }} /></div><div><span>Primary uncertainty</span><strong>{prediction.primaryUncertainty}</strong></div></div><p className="trust-disclosure">Synthetic model outputs demonstrate the architecture; they are not official operational forecasts. Production deployment requires calibrated historical campus data, backtesting, monitoring, and operator approval.</p></div></section>
}
