"use client"

import { useMemo, useState } from "react"
import { runSimulation } from "@/engine/simulationEngine"
import { formatNumber, formatPercent } from "@/lib/format"
import { focusScenarioConfiguration } from "@/lib/scenarioConfiguration"
import type { Scenario } from "@/types"

type WhatIfPanelProps = { scenario: Scenario; onApplyDuration: (durationHours: number) => void }

const durationOptions = [2, 4, 6, 8, 12]

export function WhatIfPanel({ scenario, onApplyDuration }: WhatIfPanelProps) {
  const [duration, setDuration] = useState(scenario.durationHours)
  const result = useMemo(() => {
    const simulation = runSimulation({ ...scenario, durationHours: duration })
    return simulation.snapshots[simulation.snapshots.length - 1].metrics
  }, [duration, scenario])
  const configuration = focusScenarioConfiguration(scenario)
  const curve = durationOptions.map((hours) => {
    const simulation = runSimulation({ ...scenario, durationHours: hours })
    return { hours, stability: simulation.snapshots[simulation.snapshots.length - 1].metrics.campusStability }
  })

  return <section className="what-if-panel panel section-anchor" id="what-if">
    <div className="panel-header"><div className="panel-title"><span className="panel-code">02B</span><h2>What if?</h2></div><span className="status-label">ALTERNATE FUTURES</span></div>
    <div className="what-if-body">
      <div className="library-intro"><div><h3>Change one variable</h3><p>Explore the duration before committing it to the scenario builder. Outputs are generated by the same simulation engine.</p></div><span className="analysis-tag">LIVE ENGINE OUTPUT</span></div>
      <div className="what-if-control"><label className="field-label" htmlFor="what-if-duration">{configuration.durationLabel} <output>{duration}h</output></label><input id="what-if-duration" type="range" min="2" max="12" step="2" value={duration} onChange={(event) => setDuration(Number(event.target.value))} /><div className="range-scale"><span>2h</span><span>12h</span></div></div>
      <div className="what-if-result"><div><span className="metric-label">Projected stability</span><strong>{result.campusStability}</strong></div><div><span className="metric-label">Students affected</span><strong>{formatNumber(result.affectedStudents)}</strong></div><div><span className="metric-label">Room utilization</span><strong>{formatPercent(result.roomUtilization)}</strong></div><button className="secondary-button" type="button" onClick={() => onApplyDuration(duration)} disabled={duration === scenario.durationHours}>Apply {duration}h</button></div>
      <div className="impact-curve" aria-label="Projected campus stability by closure duration">
        {curve.map((point) => <div className={`impact-curve-point ${point.hours === duration ? "active" : ""}`} key={point.hours}><div className="impact-curve-bar"><span style={{ height: `${Math.max(8, point.stability)}%` }} /></div><span>{point.hours}h</span><strong>{point.stability}</strong></div>)}
      </div>
    </div>
  </section>
}
