"""Train RIPPLE's local tabular MLP and export the exact artifact used by Next.js.

The trainer intentionally uses only the Python standard library.  It performs
real mini-batch backpropagation with ReLU hidden layers, a 70/15/15 split, and
train-only standardization.  Labels are generated by the TypeScript
deterministic RIPPLE engine before this script runs.
"""

from __future__ import annotations

import json
import math
import random
import sys
import time
from pathlib import Path

SEED = 42017
DATASET_PATH = Path("scripts/generated/neural_dataset.json")
MODEL_PATH = Path("src/data/neuralModel.json")


def finite(value):
    return isinstance(value, (int, float)) and math.isfinite(value)


def mean(values):
    return sum(values) / max(len(values), 1)


def std(values, average):
    return max(math.sqrt(sum((value - average) ** 2 for value in values) / max(len(values), 1)), 1e-8)


def relu(value):
    return value if value > 0.0 else 0.0


def relu_gradient(value):
    return 1.0 if value > 0.0 else 0.0


class MLP:
    def __init__(self, input_size, hidden_sizes, output_size, seed):
        rng = random.Random(seed)
        sizes = [input_size, *hidden_sizes, output_size]
        self.weights = []
        self.biases = []
        for left, right in zip(sizes, sizes[1:]):
            scale = math.sqrt(2.0 / left)
            self.weights.append([[rng.uniform(-scale, scale) for _ in range(left)] for _ in range(right)])
            self.biases.append([0.0 for _ in range(right)])

    def forward(self, inputs):
        activations = inputs
        caches = []
        for layer_index, (weights, biases) in enumerate(zip(self.weights, self.biases)):
            preactivation = [sum(weight * value for weight, value in zip(row, activations)) + bias for row, bias in zip(weights, biases)]
            caches.append((activations, preactivation))
            activations = preactivation if layer_index == len(self.weights) - 1 else [relu(value) for value in preactivation]
        return activations, caches

    def gradients(self, inputs, targets):
        predictions, caches = self.forward(inputs)
        delta = [2.0 * (prediction - target) / len(targets) for prediction, target in zip(predictions, targets)]
        gradients_w = [[[0.0 for _ in row] for row in weights] for weights in self.weights]
        gradients_b = [[0.0 for _ in biases] for biases in self.biases]
        for layer_index in range(len(self.weights) - 1, -1, -1):
            previous, preactivation = caches[layer_index]
            for row_index, row in enumerate(self.weights[layer_index]):
                gradients_b[layer_index][row_index] = delta[row_index]
                for column_index, previous_value in enumerate(previous):
                    gradients_w[layer_index][row_index][column_index] = delta[row_index] * previous_value
            if layer_index > 0:
                previous_delta = [0.0] * len(caches[layer_index - 1][1])
                for previous_index in range(len(previous_delta)):
                    upstream = sum(self.weights[layer_index][row_index][previous_index] * delta[row_index] for row_index in range(len(delta)))
                    previous_delta[previous_index] = upstream * relu_gradient(caches[layer_index - 1][1][previous_index])
                delta = previous_delta
        return predictions, gradients_w, gradients_b

    def apply_gradients(self, gradients_w, gradients_b, learning_rate, momentum_state, momentum=0.88):
        for layer_index in range(len(self.weights)):
            for row_index in range(len(self.weights[layer_index])):
                for column_index in range(len(self.weights[layer_index][row_index])):
                    key = (layer_index, row_index, column_index)
                    previous = momentum_state.setdefault(key, 0.0)
                    update = momentum * previous + learning_rate * gradients_w[layer_index][row_index][column_index]
                    momentum_state[key] = update
                    self.weights[layer_index][row_index][column_index] -= update
                key = (layer_index, row_index, -1)
                previous = momentum_state.setdefault(key, 0.0)
                update = momentum * previous + learning_rate * gradients_b[layer_index][row_index]
                momentum_state[key] = update
                self.biases[layer_index][row_index] -= update

    def predict(self, inputs):
        return self.forward(inputs)[0]

    def parameter_count(self):
        return sum(len(row) for weights in self.weights for row in weights) + sum(len(biases) for biases in self.biases)


def validate_dataset(dataset):
    samples = dataset["samples"]
    if len(samples) < 10000:
        raise ValueError("Dataset must contain at least 10,000 samples")
    if len(dataset["featureMetadata"]) != len(samples[0]["features"]):
        raise ValueError("Feature metadata does not match feature vectors")
    seen = set()
    ranges = [(item["min"], item["max"]) for item in dataset["featureMetadata"]]
    target_ranges = [(item["min"], item["max"]) for item in dataset["targetMetadata"]]
    for sample in samples:
        features = sample["features"]
        targets = sample["targets"]
        key = tuple(round(value, 6) for value in features)
        if key in seen:
            raise ValueError("Duplicate feature row detected")
        seen.add(key)
        for value, (minimum, maximum) in zip(features, ranges):
            if not finite(value) or value < minimum or value > maximum:
                raise ValueError("Feature value failed finite/range validation")
        for value, (minimum, maximum) in zip(targets, target_ranges):
            if not finite(value) or value < minimum or value > maximum:
                raise ValueError("Target value failed finite/range validation")


def split_dataset(samples):
    indices = list(range(len(samples)))
    random.Random(SEED).shuffle(indices)
    train_end = int(len(indices) * 0.70)
    validation_end = train_end + int(len(indices) * 0.15)
    return ([samples[index] for index in indices[:train_end]], [samples[index] for index in indices[train_end:validation_end]], [samples[index] for index in indices[validation_end:]])


def fit_scaler(samples, key):
    columns = list(zip(*(sample[key] for sample in samples)))
    averages = [mean(list(column)) for column in columns]
    deviations = [std(list(column), average) for column, average in zip(columns, averages)]
    return averages, deviations


def scale(rows, averages, deviations):
    return [[(value - average) / deviation for value, average, deviation in zip(row, averages, deviations)] for row in rows]


def unscale(row, averages, deviations):
    return [value * deviation + average for value, average, deviation in zip(row, averages, deviations)]


def metrics(model, samples, feature_means, feature_stds, target_means, target_stds):
    errors = []
    target_errors = [[] for _ in target_means]
    for sample in samples:
        prediction = unscale(model.predict(scale([sample["features"]], feature_means, feature_stds)[0]), target_means, target_stds)
        for target_index, (predicted, actual) in enumerate(zip(prediction, sample["targets"])):
            error = predicted - actual
            errors.append(error)
            target_errors[target_index].append(error)
    mae = mean([abs(error) for error in errors])
    rmse = math.sqrt(mean([error * error for error in errors]))
    return {"mae": round(mae, 6), "rmse": round(rmse, 6), "perTarget": [{"mae": round(mean([abs(error) for error in errors_for_target]), 6), "rmse": round(math.sqrt(mean([error * error for error in errors_for_target])), 6)} for errors_for_target in target_errors]}


def train_candidate(train, validation, input_size, output_size, hidden_sizes, candidate_seed):
    feature_means, feature_stds = fit_scaler(train, "features")
    target_means, target_stds = fit_scaler(train, "targets")
    model = MLP(input_size, hidden_sizes, output_size, candidate_seed)
    rng = random.Random(candidate_seed + 99)
    momentum_state = {}
    best_state = None
    best_validation = float("inf")
    last_training_loss = None
    epochs_without_improvement = 0
    for epoch in range(36):
        order = list(range(len(train)))
        rng.shuffle(order)
        batch_size = 128
        for start in range(0, len(order), batch_size):
            batch_indices = order[start:start + batch_size]
            accumulated_w = [[[0.0 for _ in row] for row in weights] for weights in model.weights]
            accumulated_b = [[0.0 for _ in biases] for biases in model.biases]
            for index in batch_indices:
                features = scale([train[index]["features"]], feature_means, feature_stds)[0]
                targets = scale([train[index]["targets"]], target_means, target_stds)[0]
                predictions, gradients_w, gradients_b = model.gradients(features, targets)
                last_training_loss = mean([(prediction - target) ** 2 for prediction, target in zip(predictions, targets)])
                for layer_index in range(len(accumulated_w)):
                    for row_index in range(len(accumulated_w[layer_index])):
                        accumulated_b[layer_index][row_index] += gradients_b[layer_index][row_index]
                        for column_index in range(len(accumulated_w[layer_index][row_index])):
                            accumulated_w[layer_index][row_index][column_index] += gradients_w[layer_index][row_index][column_index]
            divisor = max(len(batch_indices), 1)
            for layer_index in range(len(accumulated_w)):
                for row_index in range(len(accumulated_w[layer_index])):
                    accumulated_b[layer_index][row_index] /= divisor
                    for column_index in range(len(accumulated_w[layer_index][row_index])):
                        accumulated_w[layer_index][row_index][column_index] /= divisor
            learning_rate = 0.018 * (0.94 ** epoch)
            model.apply_gradients(accumulated_w, accumulated_b, learning_rate, momentum_state)
        validation_metrics = metrics(model, validation, feature_means, feature_stds, target_means, target_stds)
        if validation_metrics["mae"] < best_validation:
            best_validation = validation_metrics["mae"]
            best_state = (json.loads(json.dumps(model.weights)), json.loads(json.dumps(model.biases)))
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1
        if epochs_without_improvement >= 7:
            break
    if best_state is not None:
        model.weights, model.biases = best_state
    return model, feature_means, feature_stds, target_means, target_stds, epoch + 1, last_training_loss or 0.0


def export_model(model, feature_means, feature_stds, target_means, target_stds, dataset, train_metrics, validation_metrics, test_metrics, candidates, epochs, training_loss):
    artifact = {
        "version": "campus-operational-neural-network-v1",
        "format": "ripple-mlp-json-v1",
        "modelLabel": "Campus Operational Neural Network v1",
        "architecture": {"type": "MLP", "inputSize": len(feature_means), "hiddenLayers": [len(model.weights[0]), *[len(layer) for layer in model.weights[1:-1]],], "outputSize": len(target_means), "activation": "ReLU", "optimizer": "mini-batch SGD with momentum"},
        "featureMetadata": dataset["featureMetadata"],
        "targetMetadata": dataset["targetMetadata"],
        "dataset": {"scenarioDistribution": dataset["scenarioDistribution"], "qualityChecks": {"finiteValues": True, "rangeChecks": True, "duplicateRows": False, "minimumSampleCount": True}},
        "training": {"seed": SEED, "samples": len(dataset["samples"]), "trainSamples": len(train_metrics["_split"]), "validationSamples": len(validation_metrics["_split"]), "testSamples": len(test_metrics["_split"]), "epochs": epochs, "batchSize": 128, "learningRateSchedule": "0.018 × 0.94^epoch", "trainingLoss": round(training_loss, 6)},
        "preprocessing": {"method": "standard score", "fit": "train only", "featureMeans": feature_means, "featureStds": feature_stds, "targetMeans": target_means, "targetStds": target_stds},
        "metrics": {"train": {key: value for key, value in train_metrics.items() if key != "_split"}, "validation": {key: value for key, value in validation_metrics.items() if key != "_split"}, "test": {key: value for key, value in test_metrics.items() if key != "_split"}, "candidates": candidates},
        "model": {"weights": model.weights, "biases": model.biases},
        "parameterCount": model.parameter_count(),
        "inference": {"execution": "local TypeScript forward pass", "latencyMeasurement": "training-process CPU measurement is recorded below"},
        "limitations": ["Synthetic labels are generated by deterministic RIPPLE simulation rules.", "The model demonstrates local predictive architecture; it is not calibrated to live campus telemetry.", "Production use requires historical data, backtesting, drift monitoring, and human approval."],
    }
    artifact["training"]["trainSamples"] = len(dataset["samples"]) * 70 // 100
    artifact["training"]["validationSamples"] = len(dataset["samples"]) * 15 // 100
    artifact["training"]["testSamples"] = len(dataset["samples"]) - artifact["training"]["trainSamples"] - artifact["training"]["validationSamples"]
    serial = json.dumps(artifact, separators=(",", ":"))
    artifact["modelSizeBytes"] = len(serial.encode("utf-8"))
    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    MODEL_PATH.write_text(json.dumps(artifact, separators=(",", ":")))
    return artifact


def main():
    if not DATASET_PATH.exists():
        raise FileNotFoundError(f"Missing {DATASET_PATH}; run the TypeScript dataset generator first")
    dataset = json.loads(DATASET_PATH.read_text())
    validate_dataset(dataset)
    train, validation, test = split_dataset(dataset["samples"])
    input_size = len(dataset["featureMetadata"])
    output_size = len(dataset["targetMetadata"])
    candidate_specs = [("small", [16]), ("medium", [24, 12]), ("large", [32, 16, 8])]
    candidate_results = []
    selected = None
    for index, (name, hidden_sizes) in enumerate(candidate_specs):
        started = time.perf_counter()
        model, feature_means, feature_stds, target_means, target_stds, epochs, training_loss = train_candidate(train, validation, input_size, output_size, hidden_sizes, SEED + index * 31)
        validation_metrics = metrics(model, validation, feature_means, feature_stds, target_means, target_stds)
        result = {"name": name, "hiddenLayers": hidden_sizes, "parameters": model.parameter_count(), "epochs": epochs, "validation": validation_metrics, "trainingSeconds": round(time.perf_counter() - started, 3)}
        candidate_results.append(result)
        print(f"{name}: validation MAE {validation_metrics['mae']:.4f} / RMSE {validation_metrics['rmse']:.4f} / {result['trainingSeconds']}s")
        if selected is None or validation_metrics["mae"] + model.parameter_count() * 0.000001 < selected[0]:
            selected = (validation_metrics["mae"] + model.parameter_count() * 0.000001, model, feature_means, feature_stds, target_means, target_stds, epochs, training_loss, name)
    _, model, feature_means, feature_stds, target_means, target_stds, epochs, training_loss, selected_name = selected
    train_metrics = metrics(model, train, feature_means, feature_stds, target_means, target_stds)
    validation_metrics = metrics(model, validation, feature_means, feature_stds, target_means, target_stds)
    test_metrics = metrics(model, test, feature_means, feature_stds, target_means, target_stds)
    train_metrics["_split"] = train
    validation_metrics["_split"] = validation
    test_metrics["_split"] = test
    artifact = export_model(model, feature_means, feature_stds, target_means, target_stds, dataset, train_metrics, validation_metrics, test_metrics, candidate_results, epochs, training_loss)
    artifact["selection"] = {"selected": selected_name, "criterion": "lowest validation MAE with parameter-count tie preference; test held out until after selection"}
    MODEL_PATH.write_text(json.dumps(artifact, separators=(",", ":")))
    print(f"selected: {selected_name}")
    print(f"test: MAE {test_metrics['mae']:.4f} / RMSE {test_metrics['rmse']:.4f}")
    print(f"exported: {MODEL_PATH} ({artifact['modelSizeBytes']} bytes, {artifact['parameterCount']} parameters)")


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"training failed: {error}", file=sys.stderr)
        raise
